apiVersion: tests.testkube.io/v2
kind: TestSuite
metadata:
  name: hands-on-testkube
  namespace: testkube
  generation: 1
spec:
  description: Example Testkube test suite
  executionRequest: {}
  steps:
  - execute:
      name: postman-test
  - delay:
      duration: 1000
  - execute:
      name: k6-test-script
  - delay:
      duration: 1000
  - execute:
      name: maven-test
  - delay:
      duration: 1000
  - execute:
      name: gradle-test